<?php
/**
 * ProblemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AUDITORIA
 *
 * # Introducão  Seja bem-vindo a documentação da API do [SCANVIN](https://scanvin.com.br) para auditorias    Nossa API foi criada utilizando o padrão [REST](https://restfulapi.net/) e [HATEOAS](https://restfulapi.net/hateoas/), possibilitando a integração de seu sistema ao nosso, e está documentada abaixo.  # Como usar a API?  Logo a seguir você encontrará todos os recursos e métodos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos diretamente através dela.  # Autenticação  Você precisa de uma [API KEY](https://en.wikipedia.org/wiki/Application_programming_interface_key#HTTP_APIs) para identificar a conta que está realizando solicitações para a API. Você pode obter seu token de autenticação no seu [Painel do Cliente](https://auditoria.scanvin.com.br/client/).  Insira seu token no campo que se encontra topo desta página para testar os métodos da API.  # Webhook  Você também deve configurar seu [Webhook](https://en.wikipedia.org/wiki/Webhook) no [Painel do Cliente](https://auditoria.scanvin.com.br/client/webhook). Quando os resultados da auditoria estiverem disponíveis, uma notificação será enviada para a URL informada, via [HTTP POST](https://en.wikipedia.org/wiki/POST_(HTTP)). A notificação possui ```Content-type``` do tipo ```application/json```. O [JSON](https://en.wikipedia.org/wiki/JSON) postado contém um único campo, ```notification_id```, que contém o identificador único do evento que gerou a notificação. Deve-se então chamar o endpoint ```Inspection - Get Inspection```, informando esse mesmo identificador único, para recuperar os dados da vistoria, e da auditoria realizada.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProblemsTest Class Doc Comment
 *
 * @category    Class
 * @description Problems
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProblemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Problems"
     */
    public function testProblems()
    {
    }

    /**
     * Test attribute "extinguisher"
     */
    public function testPropertyExtinguisher()
    {
    }

    /**
     * Test attribute "hodometer"
     */
    public function testPropertyHodometer()
    {
    }

    /**
     * Test attribute "seal"
     */
    public function testPropertySeal()
    {
    }

    /**
     * Test attribute "fl_alert"
     */
    public function testPropertyFlAlert()
    {
    }

    /**
     * Test attribute "fr_alert"
     */
    public function testPropertyFrAlert()
    {
    }

    /**
     * Test attribute "rl_alert"
     */
    public function testPropertyRlAlert()
    {
    }

    /**
     * Test attribute "rr_alert"
     */
    public function testPropertyRrAlert()
    {
    }

    /**
     * Test attribute "fl_headlight"
     */
    public function testPropertyFlHeadlight()
    {
    }

    /**
     * Test attribute "fr_headlight"
     */
    public function testPropertyFrHeadlight()
    {
    }

    /**
     * Test attribute "rl_headlight"
     */
    public function testPropertyRlHeadlight()
    {
    }

    /**
     * Test attribute "rr_headlight"
     */
    public function testPropertyRrHeadlight()
    {
    }
}
